version: "3"
networks:
  mongo_netw:
    external: true
    name: mongo_netw
  frontend_netw:
    driver: bridge
    name: frontend_netw
services:
  api:
    hostname: api_service
    container_name: api_service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - 8080:21242
      - 9100:9100
    restart: always
    networks:
      - frontend_netw
      - mongo_netw
    environment:
      - PORT=21242
      - CONNECT_URL=mongodb://root:example@mongo:27017/monefly?authMechanism=DEFAULT&authSource=admin
    command: yarn dev
