version: "3"
services:
  mongo:
    container_name: Mongo-DB
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./docker/volume/mongodb:/data/db

  mongo_express:
    container_name: Mongo-UI
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: sasa1234

      ME_CONFIG_SITE_BASEURL: /ui/mongo

  node_red:
    build: ./docker/node-red/
    container_name: Node-RED
    environment:
      - http_proxy=http:/36.89.99.86:1280
    ports:
      - "1880:1880" 
    volumes:
      - ./docker/node-red/data:/data
    restart: always # Container will automaticly startup

  balancer:
    container_name: "balancer"
    image: nginx
    volumes:
      - ./docker/balancer/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/balancer/nginx.conf:/etc/nginx/nginx.conf
    #depends_on:
    #  - mongo_express
    #  - node_red
    ports:
      - "1280:80"
      - "80:80"
      - "443:443"
    links:
      - mongo_express
      - mongo
      - node_red
